version: '3.8'

services:
  postgres_db:
    image: postgres:16-alpine
    container_name: fiver_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: fivercable_db
    ports:
      - "5432:5432"

  redis_cache:
    image: redis:alpine
    container_name: fiver_redis
    ports:
      - "6379:6379"

  ms_auth:
    build:
      context: .
      dockerfile: docker/Dockerfile.auth
    container_name: ms_auth
    ports:
      - "3000:3000"
    depends_on:
      - postgres_db

  ms_catalogo:
    build:
      context: .
      dockerfile: docker/Dockerfile.catalogo
    container_name: ms_catalogo
    ports:
      - "3001:3001"
    depends_on:
      - postgres_db

  ms_pedidos:
    build:
      context: .
      dockerfile: docker/Dockerfile.pedidos
    container_name: ms_pedidos
    ports:
      - "3002:3002"
    depends_on:
      - postgres_db

  ms_pagos:
    build:
      context: .
      dockerfile: docker/Dockerfile.pagos
    container_name: ms_pagos
    ports:
      - "3003:3003"
    depends_on:
      - postgres_db
